#!/usr/bin/bash

echo -n "1 of 7 Exporting All_tweets ... "
python tweet-js.py -f tweets.js > All_tweets.txt
echo Done

echo -n "2 of 7 Exporting No_re_tweets ... "
python tweet-js.py -f tweets.js -x > No_re_tweets.txt
echo Done

echo -n "3 of 7 Exporting Hashtag_list ... "
python tweet-js.py -f tweets.js -l > Hashtag_list.txt
echo Done

echo -n "4 of 7 Exporting text_filtered_list ... "
python tweet-js.py -f tweets.js -t "زرت" > text_filtered_list.txt
echo Done

echo -n "5 of 7 Exporting hash_filtered_list ... "
python tweet-js.py -f tweets.js -# "يحدث_الآن" > hash_filtered_list.txt
echo Done

echo -n "6 of 7 Exporting date_filtered_list ... "
python tweet-js.py -f tweets.js -s "2012" -e "5-2013" > date_filtered_list.txt
echo Done

echo -n "7 of 7 Exporting multi_filtered_list ... "
python tweet-js.py -f tweets.js -# "يحدث_الآن" -s "26-2-2017" -e "28-2-2017" > multi_filtered_list.txt
echo Done
